version: '3'

services:
    api-endpoint:
        image: maven
        command: mvn clean compile quarkus:dev
        volumes:
            - ~/.m2:/root/.m2 
            - ./api-endpoint:/app
        working_dir: /app
        ports:
            - "8080:8080"
    web:
        image: node
        command: yarn serve
        volumes:
            - ./web:/app
        working_dir: /app
        ports:
            - "3000:3000"
        depends_on:
            - api-endpoint