steps:
    - name: 'gcr.io/cloud-builders/mvn'
      args: ['clean', 'package']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/rcisucon-app', '-f', './src/main/docker/Dockerfile.jvm', '.']
      timeout: 500s
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/rcisucon-app']